services:
  - type: web
    name: dashboard-solar
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    region: oregon  # o usa otra como frankfurt si estás en Europa
