name: Actualizar CSV desde FTP

on:
  schedule:
    - cron: '5,10,15,20,25 12-23 * * *'  # 7:05–20:20 hora Colombia
  workflow_dispatch:

jobs:
  update_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Descargar archivo más reciente desde FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          python3 <<EOF
          from ftplib import FTP
          import os

          ftp = FTP(os.environ['FTP_HOST'])
          ftp.login(os.environ['FTP_USER'], os.environ['FTP_PASS'])

          ftp.cwd('/ecoener-envios/disponibilidad-tr')

          # Obtener lista de archivos
          archivos = ftp.nlst()

          # Filtrar solo archivos CSV y ordenar
          archivos_csv = sorted([f for f in archivos if f.endswith('.csv')])
          archivo_mas_reciente = archivos_csv[-1]

          # Descargar el archivo más reciente y guardarlo localmente
          with open('generacion_actual.csv', 'wb') as f:
              ftp.retrbinary(f'RETR {archivo_mas_reciente}', f.write)

          ftp.quit()

          print(f"Archivo descargado: {archivo_mas_reciente}")
          EOF

      - name: Commit y push si hay cambios
        run: |
          git config user.name "AndresMachuca21"
          git config user.email "andresmachuca21@gmail.com"
          git add generacion_actual.csv || exit 0
          git commit -m "Auto-update CSV desde FTP" || exit 0
          git push
